marks = []
std1 = input("Enter a 1st student marks: ")
marks.append(std1)
std2 = input("Enter a 2nd student marks: ")
marks.append(std2)
std3 = input("Enter a 3rd student marks: ")
marks.append(std3)
std4 = input("Enter a 4th student marks: ")
marks.append(std4)
std5 = input("Enter a 5th student marks: ")
marks.append(std5)
std6 = input("Enter a 6th student marks: ")
marks.append(std6)
print("Marks = ",marks)